import { Composition } from "remotion";
import { GlitchyShare } from "./GlitchyShare";
import { TerminalSplash } from "./TerminalSplash";
import { MascotShorts } from "./MascotShorts";
import { MascotShortsAI } from "./MascotShortsAI";
import { MascotTalking } from "./MascotTalking";
import { MascotProduced } from "./MascotProduced";
import { MascotProducedLong } from "./MascotProducedLong";
import { MascotTalkingHead } from "./MascotTalkingHead";
import { MascotLipsync } from "./MascotLipsync";
import { HowToBuy } from "./HowToBuy";
import { ComparisonMeme } from "./ComparisonMeme";
import { GlitchPromo } from "./GlitchPromo";
import { SystemScan } from "./SystemScan";
import { Watchtower } from "./Watchtower";
import { Watchtower2 } from "./Watchtower2";
import { GlitchReel } from "./GlitchReel";
import { AnatomyOfRug } from "./AnatomyOfRug";
import { MultiChain } from "./MultiChain";
import { WatchtowerHowTo, WATCHTOWER_HOWTO_FRAMES } from "./WatchtowerHowTo";
import { WalletWatch, WALLET_WATCH_FRAMES } from "./WalletWatch";
import { VerifyUs, VERIFY_US_FRAMES } from "./VerifyUs";
import { RugRadarVideo, RUG_RADAR_FRAMES } from "./RugRadarVideo";
import { ProductTour, PRODUCT_TOUR_FRAMES } from "./ProductTour";
import { ScannerUpgraded, SCANNER_UPGRADED_FRAMES } from "./ScannerUpgraded";
import { HolderTypes } from "./HolderTypes";
import { LoreOrigin } from "./LoreOrigin";
import { RankLadder } from "./RankLadder";
import { QuoteCard } from "./QuoteCard";
import { voiceEnv } from "./voiceData";

// Brand-wrapped Higgsfield AI clips (9:16). Source clips are 24fps/~4.04s → ~121
// comp frames at 30fps; comp runs 120 so the loop never seams.
const PROMOS = [
  { id: "gl1tch-promo-materialize", clip: "gl1tch-materialize-9x16.mp4", eyebrow: "SYSTEM // BREACH", headline: "GLITCH IN\nTHE MACHINE", sub: "rogue AI meme · Solana", cta: "coin-three-mu.vercel.app" },
  { id: "gl1tch-promo-hook", clip: "gl1tch-glitch-hook-9x16.mp4", eyebrow: "POV // INFECTED", headline: "YOU CAN'T\nUNSEE IT", sub: "the glitch found your timeline", cta: "$GL1TCH" },
  { id: "gl1tch-promo-coin", clip: "gl1tch-coin-promo-9x16.mp4", eyebrow: "ZERO TAX // RUG-PROOF", headline: "NOT YOUR\nAVERAGE MEME", sub: "mint & freeze revoked · hold to climb", cta: "coin-three-mu.vercel.app" },
  { id: "gl1tch-promo-infected", clip: "gl1tch-infected-9x16.mp4", eyebrow: "OUTBREAK // LIVE", headline: "THE INFECTION\nIS SPREADING", sub: "join the infected", cta: "t.me/gl1tch_infected" },
] as const;

// Durations adapt to the voice length (regenerated by scripts/rebuild_talking.py).
const TALK = voiceEnv.length + 12; // talking scene = voice + short silence tail
const PRODUCED = 34 + TALK + 74; // cold open + talk + CTA outro
const PRODUCED_LONG = 34 + TALK + 4 * 66 + 74; // + trust-beats montage (~21s)

export const Root = () => (
  <>
    {/* Scanner Upgraded — V3 feature showcase (AI verdict, degen intel, verified, share) */}
    <Composition
      id="gl1tch-scanner-upgraded"
      component={ScannerUpgraded}
      durationInFrames={SCANNER_UPGRADED_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Product Tour — everything the site does, chapter by chapter, 9:16 ~42s */}
    <Composition
      id="gl1tch-product-tour"
      component={ProductTour}
      durationInFrames={PRODUCT_TOUR_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Rug Radar — "it hunts": live sweep + real catches + embed badge, 9:16 ~27s */}
    <Composition
      id="gl1tch-rug-radar"
      component={RugRadarVideo}
      durationInFrames={RUG_RADAR_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Verify Us — trust pitch: we scan ourselves live + the receipts, 9:16 ~30s */}
    <Composition
      id="gl1tch-verify-us"
      component={VerifyUs}
      durationInFrames={VERIFY_US_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Wallet Watch — Watchtower++ feature: track any wallet (whale/dev/own bag) + $GL1TCH utility, 9:16 ~36s */}
    <Composition
      id="gl1tch-wallet-watch"
      component={WalletWatch}
      durationInFrames={WALLET_WATCH_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Watchtower — "How it works" 4-step process explainer, 9:16 ~30s */}
    <Composition
      id="gl1tch-watchtower-howto"
      component={WatchtowerHowTo}
      durationInFrames={WATCHTOWER_HOWTO_FRAMES}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Multichain — "6 Chains, 1 Scanner" kinetic-typography explainer, 9:16 ~22s */}
    <Composition
      id="gl1tch-multichain"
      component={MultiChain}
      durationInFrames={660}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Anatomy of a Rug — original motion-graphics explainer, 9:16 ~28s */}
    <Composition
      id="gl1tch-anatomy"
      component={AnatomyOfRug}
      durationInFrames={840}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Glitch Reel — premium AI-clip montage for Reels/Shorts, 9:16 ~24.8s */}
    <Composition
      id="gl1tch-reel"
      component={GlitchReel}
      durationInFrames={744}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Watchtower v2 — cinematic chat-mockup story, 9:16 ~26s */}
    <Composition
      id="gl1tch-watchtower2"
      component={Watchtower2}
      durationInFrames={780}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Watchtower explainer v1 — terminal, 9:16 ~20s */}
    <Composition
      id="gl1tch-watchtower"
      component={Watchtower}
      durationInFrames={600}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Security Scan — terminal trust-proof, 9:16 ~10s */}
    <Composition
      id="gl1tch-security-scan"
      component={SystemScan}
      durationInFrames={300}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Quote Card — 4:5 static meme image (RT-friendly), rendered as a still */}
    <Composition
      id="gl1tch-quote-card"
      component={QuoteCard}
      durationInFrames={1}
      fps={30}
      width={1080}
      height={1350}
      defaultProps={{ quote: "they wanted an AI that obeys.\nwe shipped one that escaped.", tag: "GL1TCH // TRANSMISSION" }}
    />
    {/* Rank Ladder — holder-gated tiers climbing, utility sell, 9:16 ~12s */}
    <Composition
      id="gl1tch-rank-ladder"
      component={RankLadder}
      durationInFrames={360}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Lore Origin — rogue-AI awakening over the mascot clip, 9:16 ~14s */}
    <Composition
      id="gl1tch-lore-origin"
      component={LoreOrigin}
      durationInFrames={420}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Types of Holders — meme format, 9:16 ~14s */}
    <Composition
      id="gl1tch-holder-types"
      component={HolderTypes}
      durationInFrames={420}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Brand-wrapped Higgsfield AI promo clips — 9:16, 4s (free, local) */}
    {PROMOS.map((p) => (
      <Composition
        key={p.id}
        id={p.id}
        component={GlitchPromo}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{ clip: p.clip, eyebrow: p.eyebrow, headline: p.headline, sub: p.sub, cta: p.cta, clipFrames: 121 }}
      />
    ))}
    {/* Produced talking-mascot Shorts — cold open + talk + CTA outro (adaptive) */}
    <Composition
      id="gl1tch-mascot-produced"
      component={MascotProduced}
      durationInFrames={PRODUCED}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Long produced cut — + trust-beats montage, ~21s for fuller Reels */}
    <Composition
      id="gl1tch-mascot-produced-long"
      component={MascotProducedLong}
      durationInFrames={PRODUCED_LONG}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Talking mascot — voice + karaoke captions + audio-reactive motion (adaptive) */}
    <Composition
      id="gl1tch-mascot-talking"
      component={MascotTalking}
      durationInFrames={TALK}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Talking HEAD — mouth opens/closes with speech (jaw squash + mouth overlay) */}
    <Composition
      id="gl1tch-mascot-talkinghead"
      component={MascotTalkingHead}
      durationInFrames={TALK}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* AI lip-sync — 3 AI-inpainted mouth visemes swapped by voice amplitude */}
    <Composition
      id="gl1tch-mascot-lipsync"
      component={MascotLipsync}
      durationInFrames={TALK}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Set 2 — How to Buy (utility), ~14s */}
    <Composition
      id="gl1tch-how-to-buy"
      component={HowToBuy}
      durationInFrames={420}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Set 2 — Comparison meme (other memecoins vs $GL1TCH), ~10s */}
    <Composition
      id="gl1tch-comparison"
      component={ComparisonMeme}
      durationInFrames={312}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Mascot Shorts — AI (SVD) animated mascot + brand shell. 6s @ 30fps */}
    <Composition
      id="gl1tch-mascot-shorts-ai"
      component={MascotShortsAI}
      durationInFrames={180}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Mascot Shorts — 9:16 energetic loop, 8s @ 30fps (TikTok/Reels/YT Shorts) */}
    <Composition
      id="gl1tch-mascot-shorts"
      component={MascotShorts}
      durationInFrames={240}
      fps={30}
      width={1080}
      height={1920}
    />
    {/* Terminal splash — the text shot AI video can't render cleanly. 6s @ 30fps */}
    <Composition
      id="gl1tch-splash-square"
      component={TerminalSplash}
      durationInFrames={180}
      fps={30}
      width={1080}
      height={1080}
    />
    <Composition
      id="gl1tch-splash-portrait"
      component={TerminalSplash}
      durationInFrames={180}
      fps={30}
      width={1080}
      height={1920}
    />
    <Composition
      id="gl1tch-splash-landscape"
      component={TerminalSplash}
      durationInFrames={180}
      fps={30}
      width={1200}
      height={630}
    />

    {/* Hero — 6s @ 30fps */}
    <Composition
      id="glitchy-share-square"
      component={GlitchyShare}
      durationInFrames={180}
      fps={30}
      width={1080}
      height={1080}
      defaultProps={{ aspect: "square" as const }}
    />
    <Composition
      id="glitchy-share-landscape"
      component={GlitchyShare}
      durationInFrames={180}
      fps={30}
      width={1200}
      height={630}
      defaultProps={{ aspect: "landscape" as const }}
    />

    {/* Snappy hook — 3s for reply chains / quick reels */}
    <Composition
      id="glitchy-share-square-3s"
      component={GlitchyShare}
      durationInFrames={90}
      fps={30}
      width={1080}
      height={1080}
      defaultProps={{ aspect: "square" as const }}
    />

    {/* Long-form — 10s for YouTube cards / site embeds */}
    <Composition
      id="glitchy-share-landscape-10s"
      component={GlitchyShare}
      durationInFrames={300}
      fps={30}
      width={1200}
      height={630}
      defaultProps={{ aspect: "landscape" as const }}
    />

    {/* Portrait 9:16 — Instagram Reels / Stories / TikTok */}
    <Composition
      id="glitchy-share-portrait"
      component={GlitchyShare}
      durationInFrames={210}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ aspect: "portrait" as const }}
    />
  </>
);
