import type { Metadata } from "next";
import { META_TITLE, META_DESCRIPTION } from "@/content/site";
import { OFFICIAL } from "@/lib/official";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { TickerBar } from "@/components/layout/TickerBar";
import { Scanlines } from "@/components/effects/Scanlines";
import { ScrollProgress } from "@/components/effects/ScrollProgress";
import { Web3Providers } from "@/components/web3/Providers";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(OFFICIAL.SITE_URL),
  title: META_TITLE,
  description: META_DESCRIPTION,
  alternates: { canonical: "/" },
  // OG/Twitter images are generated by app/opengraph-image.tsx + twitter-image.tsx.
  openGraph: {
    title: META_TITLE,
    description: META_DESCRIPTION,
    url: OFFICIAL.SITE_URL,
    siteName: "GL1TCH",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: META_TITLE,
    description: META_DESCRIPTION,
  },
};

// Site-wide entity markup — the canonical Organization + WebSite Google uses for the
// knowledge panel and sitelinks. sameAs binds the official social accounts to the brand.
const orgJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${OFFICIAL.SITE_URL}/#organization`,
      name: "GL1TCH",
      url: OFFICIAL.SITE_URL,
      logo: `${OFFICIAL.SITE_URL}/brand/gl1tch-logo-256.png`,
      description: META_DESCRIPTION,
      sameAs: [OFFICIAL.X_URL, OFFICIAL.TG_URL, OFFICIAL.IG_URL, OFFICIAL.REDDIT_URL, OFFICIAL.GITHUB_URL],
    },
    {
      "@type": "WebSite",
      "@id": `${OFFICIAL.SITE_URL}/#website`,
      name: "GL1TCH",
      url: OFFICIAL.SITE_URL,
      description: META_DESCRIPTION,
      publisher: { "@id": `${OFFICIAL.SITE_URL}/#organization` },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }} />
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <Scanlines />
        <ScrollProgress />
        <Web3Providers>
          <Header />
          <main id="main">{children}</main>
          <Footer />
          <TickerBar />
        </Web3Providers>
        <Analytics />
      </body>
    </html>
  );
}
