import type { Metadata } from "next";
import { META_TITLE, META_DESCRIPTION } from "@/content/site";
import { OFFICIAL } from "@/lib/official";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { TickerBar } from "@/components/layout/TickerBar";
import { Scanlines } from "@/components/effects/Scanlines";
import { ScrollProgress } from "@/components/effects/ScrollProgress";
import { Web3Providers } from "@/components/web3/Providers";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(OFFICIAL.SITE_URL),
  title: META_TITLE,
  description: META_DESCRIPTION,
  alternates: { canonical: "/" },
  // OG/Twitter images are generated by app/opengraph-image.tsx + twitter-image.tsx.
  openGraph: {
    title: META_TITLE,
    description: META_DESCRIPTION,
    url: OFFICIAL.SITE_URL,
    siteName: "GL1TCH",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: META_TITLE,
    description: META_DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <Scanlines />
        <ScrollProgress />
        <Web3Providers>
          <Header />
          <main id="main">{children}</main>
          <Footer />
          <TickerBar />
        </Web3Providers>
      </body>
    </html>
  );
}
